server:
  port: 8080
  forward-headers-strategy: native

spring:
  application:
    name: personal-website
  config:
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USER}
    password: ${DATABASE_PW}
    url: jdbc:postgresql://localhost:5432/website_database
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          highlight_sql: true
  security:
    user:
      name: ${APPLICATION_USER}
      password: ${APPLICATION_PW}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

s3:
  endpoint: ${S3_ENDPOINT:}
  region: ${S3_REGION:us-east-1}
  access-key: ${S3_ACCESS_KEY:}
  secret-key: ${S3_SECRET_KEY:}
  bucket-name: ${S3_BUCKET_NAME:}