server:
  port: 8080
  forward-headers-strategy: native

spring:
  application:
    name: personal-website
  config:
    import: optional:file:.env[.properties]
  security:
    user:
      name: ${APPLICATION_USER}
      password: ${APPLICATION_PW}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    org.springframework.ai: DEBUG