name: CI/CD Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p 22 -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Run deploy script
        env:
          APPLICATION_USER: ${{ secrets.APPLICATION_USER }}
          APPLICATION_PW: ${{ secrets.APPLICATION_PW }}
          DATABASE_USER: ${{ secrets.DATABASE_USER }}
          DATABASE_PW: ${{ secrets.DATABASE_PW }}
          DEPLOY_USER: ${{ secrets.SERVER_USER }}
          DEPLOY_SERVER: ${{ secrets.SERVER_HOST }}
        run: bash deploy.sh